replicaCount: 5

image:
  repository: elementalnet/chowder
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

containers:
  clamd:
    enabled: false
  freshclam:
    enabled: true
  celeryWorker:
    enabled: true
    config: |
      broker_url = 'amqp://guest:guest@rabbitmq:5672'
      result_backend = 'rpc://'
      tasks_queues = 'chowder'
    dataVolume:
      enabled: false
      # Mount path inside the Celery worker container
      mountPath: /data
      reference:
        persistentVolumeClaim:
          claimName: your-pvc
  rest:
    enabled: false

services:
  rest:
    enabled: false
    type: ClusterIP
    port: 8080
  clamd:
    enabled: false
    type: ClusterIP
    port: 3310

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

horizontalPodAutoscaler:
  # Remember to set resources above if you enable this
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

nodeSelector: {}

tolerations: []

affinity: {}
