apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chowder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chowder.name" . }}
    helm.sh/chart: {{ include "chowder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chowder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chowder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: copy-av-databases
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
              - "cp"
              - "-rv"
              - "/var/lib/clamav/."
              - "/var/lib/clamav-empty-dir/"
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/lib/clamav-empty-dir
              name: var-lib-clamav
          resources:
{{ toYaml .Values.resources | indent 12 }}
      containers:
{{- if .Values.containers.clamd.enabled }}
        - name: clamd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - clamd
          ports:
            - name: clamd
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck-clamd.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /healthcheck-clamd.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          env:
              - name: POD_NAME
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/run/clamav
              name: var-run-clamav
            - mountPath: /var/lib/clamav
              name: var-lib-clamav
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.containers.freshclam.enabled }}
        - name: freshclam
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
              - freshclam
          livenessProbe:
            exec:
              command:
                - /healthcheck-freshclam.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          env:
              - name: POD_NAME
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/run/clamav
              name: var-run-clamav
            - mountPath: /var/lib/clamav
              name: var-lib-clamav
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.containers.celeryWorker.enabled }}
        - name: celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
              - celery-worker
          ports:
            - name: clamd
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck-celery-worker.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          env:
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                  fieldRef:
                      fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/run/clamav
              name: var-run-clamav
            - mountPath: /var/lib/clamav
              name: var-lib-clamav
              readOnly: true
            - mountPath: /celery-worker/config
              name: celery-worker
{{- if .Values.containers.celeryWorker.dataVolume.enabled }}
            - mountPath: {{ .Values.containers.celeryWorker.dataVolume.mountPath }}
              name: data-volume
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.containers.rest.enabled }}
        - name: rest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
              - rest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck-clamav-rest.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /healthcheck-clamav-rest.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          env:
              - name: POD_NAME
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.namespace
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
      volumes:
        - name: celery-worker
          configMap:
            name: {{ include "chowder.fullname" . }}-celery-worker
        - name: var-run-clamav
          emptyDir: {}
        - name: var-lib-clamav
          emptyDir: {}
{{- if .Values.containers.celeryWorker.dataVolume.enabled }}
        - name: data-volume
{{ toYaml .Values.containers.celeryWorker.dataVolume.reference | indent 10 }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
