apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chowder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "chowder.name" . }}
    helm.sh/chart: {{ include "chowder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chowder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chowder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
{{- if .Values.containers.clamd.enabled }}
        - name: {{ .Chart.Name }}-clamd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: clamd
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck-clamd.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /healthcheck-clamd.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.containers.freshclam.enabled }}
        - name: {{ .Chart.Name }}-freshclam
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - /healthcheck-freshclam.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.containers.celeryWorker.enabled }}
        - name: {{ .Chart.Name }}-celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: clamd
              containerPort: 3310
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck-celery-worker.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- if .Values.containers.rest.enabled }}
        - name: {{ .Chart.Name }}-rest
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /healthcheck-clamav-rest.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /healthcheck-clamav-rest.sh
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}